// =============================================================================
// ETBZ-49 - the customer page family and its fact bindings.
//
// Eighteen designed pages. Every slot declares the fact kinds it consumes and
// nothing else: a page cannot derive a fact, only place one it was given. The
// `structuralSha256` is the hash the canonical build measured for that page, and
// is what makes "identical content yields identical structure" checkable.
//
// GENERATED by scripts/etbz49-generate-visual-contract.mjs from
// assets/visual-system-v1/. Do not edit by hand - edit the asset and re-run.
// =============================================================================

import type { PageContract, VisualComponentContract } from './types.js';

export const PAGE_FAMILY: readonly PageContract[] = [
  {
    "page": 1,
    "id": "cover",
    "family": "cover",
    "donors": {
      "primary": "V4 agent-x-etbz-4.png",
      "secondary": ["V6 wordmark contract", "V1 whitespace"],
    },
    "bindings": [
      {
        "slotId": "cover.primaryGlyph",
        "consumedFactKinds": ["day_master_stem"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
    ],
    "structuralSha256": "e880b07dc6183efedf0b968cb4629232fe13fc4451d15bb193c8c0d9cef7dd4b",
  },
  {
    "page": 2,
    "id": "identity",
    "family": "front-matter",
    "donors": {
      "primary": "V3 identity page (contact sheet, page 02)",
      "secondary": ["V4 shell", "V5 customer copy boundary"],
    },
    "bindings": [
      {
        "slotId": "identity.parameters",
        "consumedFactKinds": ["chart_parameters"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
    ],
    "structuralSha256": "3664205076564e6e2ea3bc0cd430b3c46bf103520f2c9852ce444c28dd83c106",
  },
  {
    "page": 3,
    "id": "contents",
    "family": "front-matter",
    "donors": {
      "primary": "V3 Contents (contact sheet, page 03)",
      "secondary": ["V4 shell/type", "V5 tokens"],
    },
    "bindings": [
      {
        "slotId": "contents.entries",
        "consumedFactKinds": [],
        "derivedNothing": true,
      },
    ],
    "structuralSha256": "c492f49a7f96a7d15699dc401865814b387b054eb554d26d60ad5372a0c881be",
  },
  {
    "page": 4,
    "id": "glance",
    "family": "chart-foundation",
    "donors": {
      "primary": "V3 Chart at a Glance (contact sheet, page 04)",
      "secondary": ["V4 colour/glyph system", "V6 fact bindings"],
    },
    "bindings": [
      {
        "slotId": "glance.dayMaster",
        "consumedFactKinds": ["day_master_stem", "stem_phase", "stem_polarity"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
      {
        "slotId": "glance.pillars",
        "consumedFactKinds": ["pillar_stem", "pillar_branch"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
      {
        "slotId": "glance.wuXing",
        "consumedFactKinds": ["wu_xing_vector"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
        "presentationTransform": null,
      },
    ],
    "structuralSha256": "967a9798c7db44e489fd17efe1af1008ce347230d6b3004ee65d473559892bc3",
  },
  {
    "page": 5,
    "id": "four-pillars",
    "family": "chart-foundation",
    "donors": {
      "primary": "V4 agent-x-etbz-5.png",
      "secondary": ["V6 region-scoped colour guard", "V5 neutral pillar ground + gold selection"],
    },
    "bindings": [
      {
        "slotId": "pillars.stem[*]",
        "consumedFactKinds": ["pillar_stem", "stem_phase", "stem_polarity"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
      {
        "slotId": "pillars.branch[*]",
        "consumedFactKinds": ["pillar_branch", "branch_phase", "branch_animal_label"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
      {
        "slotId": "pillars.hidden[*]",
        "consumedFactKinds": ["hidden_stem", "hidden_stem_phase", "hidden_stem_qi_role"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
      {
        "slotId": "pillars.tenGod[*]",
        "consumedFactKinds": ["ten_god_relation"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
    ],
    "structuralSha256": "8956aff80b7d1afff9a3374dfc13b533c36265ebf659518b2c82835c2c5799dc",
  },
  {
    "page": 6,
    "id": "foundation",
    "family": "chart-foundation",
    "donors": {
      "primary": "V3 page-family architecture (chart foundation)",
      "secondary": ["V4 shell", "V2 column rhythm"],
    },
    "bindings": [
      {
        "slotId": "foundation.eight",
        "consumedFactKinds": ["pillar_stem", "pillar_branch", "stem_polarity", "stem_phase", "branch_phase"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
    ],
    "structuralSha256": "ed90c7798b2e3b716e21d9ed691366a57288e9915da6ad403775e93238faf680",
  },
  {
    "page": 7,
    "id": "day-master",
    "family": "chart-foundation",
    "donors": {
      "primary": "V4 agent-x-etbz-6.png",
      "secondary": ["V6 deterministic glyph placement", "V5 customer/evidence boundary"],
    },
    "bindings": [
      {
        "slotId": "dayMaster.hero",
        "consumedFactKinds": ["day_master_stem", "stem_phase", "stem_polarity", "day_pillar"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
      {
        "slotId": "dayMaster.reading",
        "consumedFactKinds": ["approved_interpretation:day_master"],
        "contentLayer": true,
        "maxChars": 900,
      },
      {
        "slotId": "dayMaster.pillarReading",
        "consumedFactKinds": ["approved_interpretation:day_pillar"],
        "contentLayer": true,
        "maxChars": 500,
      },
    ],
    "structuralSha256": "afdca232dd280395ffbc58fd1afa0bbc623411d00eea6f71fd13d2a8c7dd0b14",
  },
  {
    "page": 8,
    "id": "wu-xing-distribution",
    "family": "chart-foundation",
    "donors": {
      "primary": "V2 agent_x_ETBZ-4.png",
      "secondary": ["V4 palette/spacing", "V6 presentation transform", "V5 zero-is-zero copy rule"],
    },
    "bindings": [
      {
        "slotId": "wuXing.vector",
        "consumedFactKinds": ["wu_xing_vector"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
        "presentationTransform": "pt.linear-max-v1",
        "derives": [],
      },
    ],
    "structuralSha256": "7aa0236d57fc730ffab0d717578e26891262e93733a1d121fe2032b0266dda99",
  },
  {
    "page": 9,
    "id": "five-phases",
    "family": "general-education",
    "donors": {
      "primary": "V5 WuXingEducationPage (open five-part composition)",
      "secondary": ["V4 pastel atmosphere", "V6 structural prohibition of relation edges"],
    },
    "bindings": [
      {
        "slotId": "education.anchors",
        "consumedFactKinds": [],
        "derivedNothing": true,
        "personalised": false,
        "relationEdges": "structurally impossible",
      },
    ],
    "structuralSha256": "36feb93d6d16fc7616dbc85cefa400bb00c492f3411c25bab27416494af68d3f",
  },
  {
    "page": 10,
    "id": "ten-gods",
    "family": "chart-foundation",
    "donors": {
      "primary": "V3 Ten Gods & Hidden Stems (contact sheet, page 08)",
      "secondary": ["V5 InformationalCjkText contract", "V6 fail-closed facts", "V4 tokens"],
    },
    "bindings": [
      {
        "slotId": "tenGods.presence",
        "consumedFactKinds": ["ten_god_relation", "hidden_stem_ten_god_relation"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
        "cjkRole": "InformationalCjkText",
      },
    ],
    "structuralSha256": "34042e9ba3d187da37e6d15b9a80459a6930e516c97a38fbabec5ad3357fc9b2",
  },
  {
    "page": 11,
    "id": "hidden-stems",
    "family": "chart-foundation",
    "donors": {
      "primary": "V3 Ten Gods & Hidden Stems (contact sheet, page 08)",
      "secondary": ["V4 display glyphs + phase fields", "V5 InformationalCjkText", "V6 fail-closed"],
    },
    "bindings": [
      {
        "slotId": "hidden.rows",
        "consumedFactKinds": [
          "pillar_branch",
          "hidden_stem",
          "hidden_stem_phase",
          "hidden_stem_qi_role",
          "hidden_stem_ten_god_relation",
        ],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
    ],
    "structuralSha256": "3ab6e1de09aa4cad52cf6d9f83eb26c1313b3eea8a10dcee52eaca7690fd5f30",
  },
  {
    "page": 12,
    "id": "longform-general-education-chapter-v1-p1",
    "family": "long-form",
    "donors": {
      "primary": "V2 agent_x_ETBZ-6.png (editorial rhythm)",
      "secondary": ["V6 deterministic pagination", "V5 page budgets / text floor", "V4 palette"],
    },
    "bindings": [
      {
        "slotId": "chapter.longForm",
        "visualType": "longFormBlocks",
        "consumedFactKinds": ["approved_interpretation:chapter"],
        "fixture": "bazodiac-final/fixture/long-form/general-education-chapter-v1",
        "derivedNothing": true,
      },
    ],
    "structuralSha256": "a8e8e1df0669c167e313d36e77aa9e068bc45b7ac20df4a1eb4d06807ebfb80b",
  },
  {
    "page": 13,
    "id": "longform-general-education-chapter-v1-p2",
    "family": "long-form",
    "donors": {
      "primary": "V2 agent_x_ETBZ-6.png (editorial rhythm)",
      "secondary": ["V6 deterministic pagination", "V5 page budgets / text floor", "V4 palette"],
    },
    "bindings": [
      {
        "slotId": "chapter.longForm",
        "visualType": "longFormBlocks",
        "consumedFactKinds": ["approved_interpretation:chapter"],
        "fixture": "bazodiac-final/fixture/long-form/general-education-chapter-v1",
        "derivedNothing": true,
      },
    ],
    "structuralSha256": "97890b48aeef625e67c88bc0b43e2e46c2d51bc30456d4d822503b9ddefdb799",
  },
  {
    "page": 14,
    "id": "longform-general-education-chapter-v1-p3",
    "family": "long-form",
    "donors": {
      "primary": "V2 agent_x_ETBZ-6.png (editorial rhythm)",
      "secondary": ["V6 deterministic pagination", "V5 page budgets / text floor", "V4 palette"],
    },
    "bindings": [
      {
        "slotId": "chapter.longForm",
        "visualType": "longFormBlocks",
        "consumedFactKinds": ["approved_interpretation:chapter"],
        "fixture": "bazodiac-final/fixture/long-form/general-education-chapter-v1",
        "derivedNothing": true,
      },
    ],
    "structuralSha256": "675ae80a56c4c6deae22ae966fe066f4767f9c05c11c5c711229ae8d4faf64b3",
  },
  {
    "page": 27,
    "id": "reflection",
    "family": "reflection-closure",
    "donors": {
      "primary": "V3 Guidance & closure section (contact sheet IA)",
      "secondary": ["V4 shell", "V2 whitespace rhythm"],
    },
    "bindings": [
      {
        "slotId": "reflection.prompts",
        "consumedFactKinds": [],
        "derivedNothing": true,
        "contentClass": "GENERAL_EDUCATION",
      },
    ],
    "structuralSha256": "faf66174d8572086eee3e114afcb4de37e80a380d3867107833da1e589e269b2",
  },
  {
    "page": 28,
    "id": "summary",
    "family": "reflection-closure",
    "donors": {
      "primary": "V3 closing page summary column",
      "secondary": ["V4 shell", "V6 fact bindings"],
    },
    "bindings": [
      {
        "slotId": "summary.facts",
        "consumedFactKinds": [
          "day_master_stem",
          "pillar_stem",
          "pillar_branch",
          "wu_xing_vector",
          "chart_parameters",
        ],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
    ],
    "structuralSha256": "e121f6ad3cbcde404f1c564ec036659a50e1b0d1e3a33900177559ae866f4a98",
  },
  {
    "page": 29,
    "id": "closing",
    "family": "reflection-closure",
    "donors": {
      "primary": "V3 closing reflection (contact sheet, page 28) — sense of resolution",
      "secondary": ["V4 cover atmosphere (light, not full black)", "V6 static wordmark"],
    },
    "bindings": [
      {
        "slotId": "closing.name",
        "consumedFactKinds": ["customer_display_name"],
        "fixture": "bazodiac-final/fixture/chart/v4-mixed-v1",
      },
    ],
    "structuralSha256": "eb6618f0ee450cb6a02db49d263318627a8147419cf04ff4bd9b782c77e0e03f",
  },
  {
    "page": 30,
    "id": "method-note",
    "family": "reflection-closure",
    "donors": {
      "primary": "V3 method note / symbol key IA",
      "secondary": ["V5 customer copy boundary (no internal states)", "V4 shell"],
    },
    "bindings": [
      {
        "slotId": "method.conventions",
        "consumedFactKinds": [],
        "derivedNothing": true,
      },
    ],
    "structuralSha256": "357c153d59d7a610d79cacdb3467426456afca2abc6b2a3007066d732ded6f48",
  },
] as const;

export const VISUAL_COMPONENTS: Readonly<Record<string, VisualComponentContract>> = {
  "Wordmark": {
    "donors": {
      "primary": "V4 wordmark variant B (bazodiac_soft_editorial_v1_1 notes, 02-wordmarks)",
      "secondary": ["V6 wordmark.ts static contract"],
    },
    "asset": "assets/wordmark.svg",
    "rules": [
      "static",
      "chart-independent",
      "no glyph slot",
      "gold point 0.4×cap on baseline",
      "tracking 0.34em",
    ],
    "sha256": "sha256:c542552e8bd54033107b42132d907a48f9c5383736683edd65746b47ae7466e1",
  },
  "BazodiacDisplayGlyphSet": {
    "donors": {
      "primary": "V6 assets/etbz43/glyphs pipeline",
      "secondary": [
        "V4 agent-x-etbz-3.png (visual target: Noto Sans SC 900 + ink pass)",
        "V5 10-glyph-system.md",
      ],
    },
    "count": 27,
    "manifest": "glyphs/manifest.json",
    "manifestSha256": "sha256:54f0ed0d5d3eebf65817c13cb54ea814049c2e79c05d9d040889c69bd08005d9",
    "regionPolicy": "CN_SIMPLIFIED",
    "status": "HUMAN_PO_GLYPH_STYLE_APPROVAL_REQUIRED",
    "guard": "DISPLAY_GLYPH_OUT_OF_CONTRACT for any other codepoint",
  },
  "InformationalCjkText": {
    "donors": {
      "primary": "V5 15-informational-cjk-text.md",
      "secondary": ["V4 Noto Sans SC 400/500 decision"],
    },
    "face": "Noto Sans CJK SC 400/500",
    "usage": ["Ten Gods", "Hidden Stem terminology", "labels", "explanatory Chinese"],
    "neverRoutedThrough": "BazodiacDisplayGlyphSet",
  },
  "RunningHead": {
    "donors": {
      "primary": "V4 head (brand · customer, tag)",
      "secondary": ["V5 customer copy boundary: no SAMPLE tag on customer surface"],
    },
    "tags": ["Your chart", "Your reading", "General education"],
  },
  "AtmosphericForm": {
    "donors": {
      "primary": "V4 cover blobs",
    },
    "tokens": ["atmos-*"],
    "rule": "decorative only; never binds a fact; removed from data stages (V4 v1.1 LAW 5)",
  },
  "PhaseField": {
    "donors": {
      "primary": "V4 halos",
      "secondary": ["V5 field/mark tokens", "V6 region-scope guard"],
    },
    "tokens": ["phase-*-field", "phase-*-mark"],
    "rule": "classifies exactly one fact-bearing region (stem | branch | hidden stem); never a pillar",
  },
  "Pillar": {
    "donors": {
      "primary": "V4 agent-x-etbz-5.png",
      "secondary": ["V5 neutral ground + gold selection", "V6 guards"],
    },
    "container": "paper-100",
    "selected": {
      "container": "paper-200",
      "edge": "gold-500 0.35mm",
      "isPhase": false,
    },
    "rows": ["stem", "branch", "hiddenStems", "tenGod"],
  },
  "HiddenStemChip": {
    "donors": {
      "primary": "V4 chips",
      "secondary": ["V3 Qi-order rows", "V6 BLOCKED state"],
    },
    "fields": ["glyph", "pinyin"],
    "order": "Qi order: principal, central, residual",
    "blocked": "phase missing → neutral field, no inheritance",
  },
  "DayMasterStage": {
    "donors": {
      "primary": "V4 agent-x-etbz-6.png",
    },
    "stage": "paper-200 left column",
    "halo": "single phase field of the Day Master",
    "fullPageBlack": false,
    "darkPanel": "one compact 'Good to know' panel",
  },
  "ContentSlot": {
    "donors": {
      "primary": "V4 interpretive slots",
      "secondary": ["V5 47-customer-copy-boundary"],
    },
    "customerVisibleLabels": ["Your reading · Day Master", "Your reading · Day pillar"],
    "hiddenOnCustomer": ["max chars", "slot ids", "content-layer notes"],
    "maxChars": {
      "dayMaster": 900,
      "dayPillar": 500,
    },
  },
  "WuXingRing": {
    "donors": {
      "primary": "V2 agent_x_ETBZ-4.png",
      "secondary": ["V4 palette/spacing", "V6 presentation transform", "V5 45-presentation-transform.md"],
    },
    "transform": {
      "id": "pt.linear-max-v1",
      "discRadiusMm": "11 + 7·v/max",
      "bar": "v/max",
      "monotonic": true,
      "recomputes": false,
      "infers": [],
    },
    "zeroRule": "0 → '0.0 in this distribution'",
    "allFiveVisible": true,
  },
  "FivePhaseAnchors": {
    "donors": {
      "primary": "V5 WuXingEducationPage",
      "secondary": ["V4 pastel discs", "V6 structural prohibition of relation edges"],
    },
    "relationEdges": false,
    "star": false,
    "shengKe": "excluded (METHOD_SCOPE_BLOCKED, developer surface only)",
  },
  "TenGodsMatrix": {
    "donors": {
      "primary": "V3 Ten Gods & Hidden Stems",
      "secondary": ["V5 InformationalCjkText", "V6 fail-closed"],
    },
    "rows": 10,
    "marks": {
      "filled": "visible stem",
      "open": "hidden stem",
      "rule": "not present",
    },
  },
  "HiddenStemRows": {
    "donors": {
      "primary": "V3 Hidden Stems by Branch",
    },
    "perHiddenPhaseMark": true,
  },
  "LongForm": {
    "donors": {
      "primary": "V2 agent_x_ETBZ-6.png",
      "secondary": [
        "V6 paginate.ts contract",
        "V5 50-long-form-pagination.md",
        "V4 short-final-page reference panel",
      ],
    },
    "opener": "two balanced columns (82mm) under header",
    "continuation": "104mm column + 60mm sidebar",
    "modules": [
      "pullQuote (atomic, gold rules)",
      "keyInsight (atomic, ink-900 panel)",
      "chapterReference (sidebar / short final page)",
    ],
    "rules": {
      "source": "V1–V6 convergence (ETBZ-43)",
      "textFloorPt": 9,
      "scaleLock": 1,
      "orphanMinLines": 2,
      "widowMinLines": 2,
      "regionPolicy": "CN_SIMPLIFIED",
    },
    "paginator": "build/paginate.py",
  },
  "Contents": {
    "donors": {
      "primary": "V3 Contents",
      "secondary": ["V4 type"],
    },
    "pages": 30,
    "luckPillars": false,
  },
  "ChartAtAGlance": {
    "donors": {
      "primary": "V3 Chart at a Glance",
      "secondary": ["V4 colour/glyph system", "V6 bindings"],
    },
  },
  "Closing": {
    "donors": {
      "primary": "V3 closing reflection",
      "secondary": ["V4 light atmosphere (no full-page black)"],
    },
  },
  "DeveloperProof": {
    "donors": {
      "primary": "V6 docs/evidence + receipts",
      "secondary": ["V5 dev contact sheet"],
    },
    "pages": [
      "glyph proof",
      "glyph style decision",
      "wordmark",
      "bindings",
      "negative guards",
      "wu-xing zero case",
      "V6 fixture long-form ×2",
      "layout evidence ×2",
      "receipts",
    ],
  },
} as const;

export const CUSTOMER_SURFACE_FORBIDDEN = [
  "hashes",
  "fixture labels",
  "METHOD_SCOPE_BLOCKED",
  "rule ids",
  "font provenance",
  "slot chrome",
  "pipeline status",
] as const;

export const DEVELOPER_SURFACE_CONTAINS = [
  "glyph manifest",
  "licence proof",
  "structural hashes",
  "render receipts",
  "fixture ids",
  "blocked-state tests",
  "layout evidence",
] as const;

/** Confluence 66650114 v2 section 15. Each entry is a thing the MVP must not draw. */
export const HARD_EXCLUSIONS = [
  "Luck Pillars / Da Yun / Liu Nian",
  "general Sheng/Ke graphic",
  "Western/Fusion/transit visuals",
  "whole-column phase tint",
  "customer Day Master as brand",
  "AI-generated Hanzi",
  "faux-Asian ornament",
  "design-side BaZi calculation",
  "status/proof chrome on customer surface",
  "shrink-to-fit, clipping, overlap, silent deletion, semantic shortening",
  "per-customer layout variants",
] as const;
