// =============================================================================
// ETBZ-49 - the long-form pagination contract.
//
// Rules only. Laying out a chapter is a renderer concern (ETBZ-55); what lives
// here is what a laid-out chapter must satisfy, plus the two recovered fixture
// RESULTS that the canonical build measured, with their per-page line counts.
//
// The rules are negative by design: no shrink-to-fit, no clipping, no semantic
// shortening. A layout that needs any of them has failed, not adapted.
//
// GENERATED by scripts/etbz49-generate-visual-contract.mjs from
// assets/visual-system-v1/. Do not edit by hand - edit the asset and re-run.
// =============================================================================

import type { LongFormFixtureResult, PaginationRules } from './types.js';

export const PAGINATION_REPORT_VERSION = "bazodiac-final-pagination-report@1.0.0" as const;

export const PAGINATION_RULES: PaginationRules = {
  "orphanMinLines": 2,
  "widowMinLines": 2,
  "keepWithNextLines": 2,
  "atomic": ["pullQuote", "keyInsight"],
  "shrinkToFit": false,
  "clipping": false,
  "semanticShortening": false,
  "hyphenation": false,
  "justification": false,
  "minBandLines": 8,
  "shortFinalPageRule": "fill < 60% receives chapter reference panel (no stretch, no shrink)",
} as const;

/** The customer stress fixture and the V6 continuity fixture, as measured. */
export const LONG_FORM_FIXTURE_RESULTS: readonly LongFormFixtureResult[] = [
  {
    "fixtureId": "bazodiac-final/fixture/long-form/general-education-chapter-v1",
    "surface": "customer",
    "wordCount": 749,
    "pages": 3,
    "lines": 89,
    "findings": [],
    "structuralSha256": "sha256:4c60d30221575e5655936c49b9f4be20a6b016ac5af2770d5a29a7ff0b6174eb",
    "pageLineCounts": [48, 38, 3],
    "pageTemplates": ["opener", "continuation", "continuation"],
  },
  {
    "fixtureId": "etbz43/fixture/long-form/pagination-stress-v1",
    "surface": "developer",
    "wordCount": 679,
    "pages": 2,
    "lines": 79,
    "findings": [],
    "structuralSha256": "sha256:e522317a14e4003832b0fb4b4591534d8674d0b5d252d099c22492329e9bf18d",
    "pageLineCounts": [49, 30],
    "pageTemplates": ["opener", "continuation"],
  },
] as const;

/** Confluence 66650114 v2 section 12: a realistic chapter is 600-900 words over 2-3 pages. */
export const LONG_FORM_WORD_BUDGET = { min: 600, max: 900 } as const;
export const LONG_FORM_PAGE_BUDGET = { min: 2, max: 3 } as const;
