// =============================================================================
// ETBZ-49 - what this visual system is, and what is still open.
//
// The convergence shares are the PO decision recorded in Confluence 66650114 v2.
// The glyph-style approval is a HUMAN gate: nothing in this repository may set it
// to approved, and the implementation does not wait for it.
//
// GENERATED by scripts/etbz49-generate-visual-contract.mjs from
// assets/visual-system-v1/. Do not edit by hand - edit the asset and re-run.
// =============================================================================

import type { ConvergenceShares } from './types.js';

export const CANONICAL_DECISION_SOURCE = {
  "system": "confluence",
  "pageId": "66650114",
  "version": "2",
  "title": "ETBZ-43 — Bazodiac PDF Visual System Final Convergence v1",
} as const;

export const CONVERGENCE_SHARES: ConvergenceShares = {
  "V4": 0.35,
  "V6": 0.25,
  "V3": 0.2,
  "V2": 0.12,
  "V5": 0.06,
  "V1": 0.02,
} as const;

export const DESIGN_SYSTEM_VERSION = "1.0.0" as const;
export const DESIGN_SYSTEM_STATUS = "PO analysis-selected composite — implementation candidate; not release acceptance" as const;

/**
 * Upstream provenance of the five vendored Inter binaries, verified by byte
 * comparison against the official rsms/inter v4.1 release archive.
 */
export const FONT_LICENSE_PROVENANCE = {
  "status": "VERIFIED",
  "family": "Inter",
  "upstreamRepository": "https://github.com/rsms/inter",
  "release": "v4.1",
  "releaseCommit": "9221beed3e5b521ce94050ca542f568755c17c22",
  "archive": "Inter-4.1.zip",
  "archiveSha256": "sha256:9883fdd4a49d4fb66bd8177ba6625ef9a64aa45899767dde3d36aa425756b11e",
  "archiveInnerPath": "extras/ttf/",
  "licence": "SIL Open Font License 1.1",
  "licenceFile": "fonts/OFL.txt",
  "licenceSha256": "sha256:262481e844521b326f5ecd053e59b98c8b2da78c8ee1bdbb6e8174305e54935a",
  "versionString": "Version 4.001;git-9221beed3",
} as const;

/**
 * OPEN. The 金土木 reference face of the V4 donor was never identified; these
 * assets are a licensed, deterministic approximation of that look. Only a human
 * PO closes this, and only outside this repository.
 */
export const HUMAN_PO_GLYPH_STYLE_APPROVAL_REQUIRED = 'OPEN' as const;
