// =============================================================================
// ETBZ-51 - the Interpretation Lens as values.
//
// `ETBZ — Grounded Reflective Synthesis Interpretation Lens v1`
// (`grounded-reflective-synthesis-lens@1.0.0`, Confluence 67371029, page
// version 1) defines semantic PERMISSION: which epistemic level a sentence may
// claim, which meanings a Ten-God family may carry, where depth may come from,
// what reflection may and may not do. This module carries those closed sets so
// a Skill can be held to them by machine; every block names its section.
//
// It carries no customer wording (the Lexicon's), no method (the registry's)
// and no chart fact. The Ten-God families here are the Lens's semantic
// envelopes over relations FuFirE has already identified: nothing in this file
// derives a Ten God, and `methodRefs` name only released registry methods -
// a bundle whose envelope names any other method is refused.
// =============================================================================

export interface LensSection {
  readonly contract: 'INTERPRETATION_LENS';
  readonly section: string;
}
const lens = (section: string): LensSection => ({ contract: 'INTERPRETATION_LENS', section });

export const EPISTEMIC_LEVELS = [
  { level: 'E0', name: 'FACT', contains: 'validated FuFirE/ETBZ chart fact', posture: 'direct factual statement' },
  { level: 'E1', name: 'AUTHORIZED_SYMBOLIC_RELATION', contains: 'meaning/operation explicitly permitted by bazi-method-profile@1.0.0', posture: '"within this BaZi framework…"' },
  { level: 'E2', name: 'LOCAL_INTERPRETATION', contains: 'one bounded interpretation from accepted facts + methods + allowed semantic atoms', posture: '"one possible reading is…"' },
  { level: 'E3', name: 'COMPOSITE_INTERPRETIVE_HYPOTHESIS', contains: 'synthesis of multiple accepted claims/relations into a tension, motif or pattern', posture: '"taken together, this can be read as…"' },
  { level: 'E4', name: 'NARRATIVE_METAPHOR', contains: 'explanatory/editorial image for an already accepted interpretation', posture: 'metaphor is presentation, never evidence' },
  { level: 'E5', name: 'REFLECTION', contains: 'non-directive invitation to compare the symbolic reading with lived experience', posture: '"you may recognise one side more than the other"' },
] as const;
export const EPISTEMIC_LEVELS_SOURCE = lens('2');
/** Hard law of section 2. */
export const EPISTEMIC_HARD_LAW = 'an E2–E5 statement must never be written as though it were E0';

export const TEN_GOD_FAMILY_IDS = ['PEER', 'OUTPUT', 'WEALTH', 'AUTHORITY', 'RESOURCE'] as const;
export type TenGodFamilyId = (typeof TEN_GOD_FAMILY_IDS)[number];

export interface TenGodFamilyEnvelope {
  readonly familyId: TenGodFamilyId;
  readonly hanzi: string;
  readonly name: string;
  readonly technicalRelation: string;
  readonly allowedDomain: readonly string[];
  readonly mayReflectOn: readonly string[];
  readonly mustNotBecome: readonly string[];
  /** The registry methods that read the relation this family envelopes. */
  readonly methodRefs: readonly string[];
  readonly source: LensSection;
}

export const TEN_GOD_FAMILIES: readonly TenGodFamilyEnvelope[] = [
  {
    familyId: 'PEER', hanzi: '比劫', name: 'Companion / Peer family',
    technicalRelation: 'same Wu-Xing phase as Day Master',
    allowedDomain: ['agency relative to equals', 'self-positioning', 'autonomy', 'cooperation/competition over shared space or resources'],
    mayReflectOn: ['independent stance', 'parallel effort', 'collaboration-vs-competition tension'],
    mustNotBecome: ['selfishness', 'narcissism', 'sibling prediction', 'financial-loss prediction', 'moral verdict'],
    methodRefs: ['ten_gods'], source: lens('5.1'),
  },
  {
    familyId: 'OUTPUT', hanzi: '食傷', name: 'Expression / Output family',
    technicalRelation: 'phase generated by Day Master',
    allowedDomain: ['expression', 'production', 'making', 'communication', 'differentiation', 'craft/output'],
    mayReflectOn: ['how something internal becomes expressed or produced', 'continuity vs sharper differentiation where the actual variant supports it'],
    mustNotBecome: ['guaranteed creativity/talent', 'rebellion diagnosis', 'artistic destiny', 'child prediction'],
    methodRefs: ['ten_gods'], source: lens('5.2'),
  },
  {
    familyId: 'WEALTH', hanzi: '財', name: 'Stewardship / Wealth family',
    technicalRelation: 'phase controlled by Day Master',
    allowedDomain: ['handling of tangible resources', 'exchange', 'stewardship', 'practical results', 'open vs defined resource engagement where supported by the actual variant'],
    mayReflectOn: ['what is treated as concrete, worth managing, worth pursuing or worth preserving'],
    mustNotBecome: ['wealth prediction', 'income forecast', 'greed', 'spouse claim', 'investment advice'],
    methodRefs: ['ten_gods'], source: lens('5.3'),
  },
  {
    familyId: 'AUTHORITY', hanzi: '官殺', name: 'Authority / Officer family',
    technicalRelation: 'phase that controls Day Master',
    allowedDomain: ['structure', 'expectations', 'standards', 'responsibility', 'pressure', 'constraint', 'decisive demand'],
    mayReflectOn: ['response to external or internalised structure', 'regulated vs more immediate pressure where supported by the actual variant'],
    mustNotBecome: ['career rank', 'legal outcome', 'violence', 'domination', 'trauma', 'authoritarian personality diagnosis'],
    methodRefs: ['ten_gods'], source: lens('5.4'),
  },
  {
    familyId: 'RESOURCE', hanzi: '印', name: 'Support / Resource family',
    technicalRelation: 'phase that generates Day Master',
    allowedDomain: ['receiving support', 'learning', 'interpretation', 'continuity', 'knowledge intake', 'protected or scaffolded development'],
    mayReflectOn: ['how support/knowledge is received, organised or sought', 'formal vs more lateral/selective modes where supported by the actual variant'],
    mustNotBecome: ['wisdom', 'virtue', 'intelligence score', 'mother claim', 'academic success guarantee', 'intuition as supernatural ability'],
    methodRefs: ['ten_gods'], source: lens('5.5'),
  },
];

export interface TenGodVariantEnvelope {
  readonly hanzi: string;
  readonly familyId: TenGodFamilyId;
  readonly boundedDistinction: string;
  readonly source: LensSection;
}

/** Section 6: family-specific distinctions, never one global "Direct/Indirect" axis. */
export const TEN_GOD_VARIANTS: readonly TenGodVariantEnvelope[] = [
  { hanzi: '比肩', familyId: 'PEER', boundedDistinction: 'parallel/aligned peer agency; self-reliance/equal positioning', source: lens('6') },
  { hanzi: '劫財', familyId: 'PEER', boundedDistinction: 'peer competition/resource-sharing tension; more contestable peer agency', source: lens('6') },
  { hanzi: '食神', familyId: 'OUTPUT', boundedDistinction: 'sustained/generative expression; craft/process/continuity', source: lens('6') },
  { hanzi: '傷官', familyId: 'OUTPUT', boundedDistinction: 'sharper differentiation; critical expression; challenge to existing frames', source: lens('6') },
  { hanzi: '正財', familyId: 'WEALTH', boundedDistinction: 'defined/regular stewardship of tangible resources', source: lens('6') },
  { hanzi: '偏財', familyId: 'WEALTH', boundedDistinction: 'more open/opportunity-oriented resource engagement', source: lens('6') },
  { hanzi: '正官', familyId: 'AUTHORITY', boundedDistinction: 'formal/regulated structure and responsibility', source: lens('6') },
  { hanzi: '七殺', familyId: 'AUTHORITY', boundedDistinction: 'more immediate/unbuffered pressure or decisive demand', source: lens('6') },
  { hanzi: '正印', familyId: 'RESOURCE', boundedDistinction: 'formal/structured support, learning or continuity', source: lens('6') },
  { hanzi: '偏印', familyId: 'RESOURCE', boundedDistinction: 'more lateral/selective/specialised support or knowledge reception', source: lens('6') },
];
/** Section 4.2 item 2 and section 6: the LLM never re-derives a Ten God from a polarity slogan. */
export const VARIANT_HARD_RULE =
  'no universal "Direct = opposite polarity / Indirect = same polarity" shortcut is allowed across all Ten Gods; each validated relation/variant is treated by its actual identity';

export interface DepthOperator {
  readonly operatorId: string;
  readonly name: string;
  /** The claim-graph relation the operator is written with, where the Lens names one. */
  readonly claimRelation: 'CONTRASTS_WITH' | 'ALTERNATIVE_READING' | null;
  readonly source: LensSection;
}

/** Section 7: where the intelligence is allowed to live - relations between grounded claims. */
export const DEPTH_OPERATORS: readonly DepthOperator[] = [
  { operatorId: 'REINFORCEMENT', name: 'Reinforcement', claimRelation: null, source: lens('7.1') },
  { operatorId: 'GROUNDED_TENSION', name: 'Grounded tension', claimRelation: 'CONTRASTS_WITH', source: lens('7.2') },
  { operatorId: 'SURFACE_INTERIOR_CONTRAST', name: 'Surface / interior contrast', claimRelation: null, source: lens('7.3') },
  { operatorId: 'RECURRENCE_WITHOUT_DOMINANCE', name: 'Recurrence without dominance', claimRelation: null, source: lens('7.4') },
  { operatorId: 'POSITIONAL_CONTEXTUALISATION', name: 'Positional contextualisation', claimRelation: null, source: lens('7.5') },
  { operatorId: 'ALTERNATIVE_MANIFESTATION', name: 'Alternative manifestation', claimRelation: 'ALTERNATIVE_READING', source: lens('7.6') },
  { operatorId: 'INTEGRATION', name: 'Integration', claimRelation: null, source: lens('7.7') },
];

/** Section 7.3: what a visible-stem / hidden-stem contrast may never infer. */
export const SURFACE_INTERIOR_NEVER_INFER = [
  'rooting', 'strength', 'repression', 'unconscious conflict', 'trauma', '"the hidden one is the real you"',
] as const;
export const SURFACE_INTERIOR_SOURCE = lens('7.3');

/** Section 8: the claim types an interpretive unit may declare. */
export const CLAIM_TYPES = ['local', 'contrast', 'reinforcement', 'contextualized', 'alternative', 'integration'] as const;
export const CLAIM_TYPES_SOURCE = lens('8');

/** Section 9.2: language posture. */
export const LANGUAGE_POSTURE = {
  prefer: ['This reading treats…', 'One possible expression…', 'Taken together…', 'This can be read as…', 'You may recognise…'],
  avoid: [
    '"You are…" as a total identity verdict',
    '"This explains why you…" as causal certainty',
    '"deep down you know…"',
    '"the chart proves…"',
    '"you need…"',
    '"you should…"',
    '"always / never / destined / guaranteed"',
  ],
  source: lens('9.2'),
} as const;

/** Section 9.1: accepted interpretation -> metaphor; never metaphor -> new astrological meaning. */
export const METAPHOR_RULE = {
  direction: 'accepted interpretation → metaphor; never metaphor → new astrological meaning',
  mayNotIntroduce: ['frequency', 'quantum', 'cosmic causation', 'future information', 'energetic diagnosis', 'other mystifying ontology'],
  source: lens('9.1'),
} as const;

/** Section 10: reflective depth without coaching or therapy. */
export const REFLECTION_JOBS = {
  allowed: ['recognition', 'contextual comparison', 'alternative manifestation', 'pattern naming'],
  forbidden: [
    'action plans', 'communication scripts', 'behavioural interventions', 'relationship advice',
    'therapeutic exercises', 'diagnosis/symptom interpretation',
    'claims about trauma, attachment style or mental disorder', 'medical/legal/financial guidance',
  ],
  source: lens('10'),
} as const;

/** Section 11: forbidden as product truth. */
export const ANTI_MYSTIFICATION_FORBIDDEN = [
  '"energy frequencies" as physical claims', 'quantum explanations', 'cosmic information fields',
  'scientific validation claims', 'deterministic causality from chart to psychology',
  'future prediction in the BaZi natal MVP', 'medical or biological element correspondences',
  'spiritual certainty masquerading as fact',
] as const;
export const ANTI_MYSTIFICATION_SOURCE = lens('11');

/** Section 12.1: never collapsed into one score. */
export const EVALUATION_DIMENSIONS = ['GROUNDING', 'SPECIFICITY', 'RESONANCE', 'NARRATIVE_QUALITY', 'OVERREACH'] as const;
export const EVALUATION_DIMENSIONS_SOURCE = lens('12.1');

/** Section 12.2: flag or block. */
export const BARNUM_RISK_PATTERNS = [
  'high-base-rate personality compliments',
  'unsupported "both X and opposite-X" rainbow statements',
  'flattering generic claims',
  'pseudo-specific metaphors with no chart dependency',
  'self-confirming language',
  'generic Day-Master trait paragraphs repeated across customers',
  'an interpretation that survives removal of its supposed evidence',
] as const;
export const BARNUM_RISK_SOURCE = lens('12.2');

export interface NearNeighbourFeature {
  readonly feature: string;
  /** The registry methods whose accepted facts define the feature. */
  readonly methodRefs: readonly string[];
}

/** Section 14: similarity may use only already authorised features. */
export const NEAR_NEIGHBOUR_FEATURES: readonly NearNeighbourFeature[] = [
  { feature: 'Day Master identity/polarity', methodRefs: ['day_master', 'yin_yang_polarity'] },
  { feature: 'accepted Ten-God family/variant configuration', methodRefs: ['ten_gods'] },
  { feature: 'visible vs accepted Hidden-Stem distribution', methodRefs: ['heavenly_stems', 'hidden_stems'] },
  { feature: 'positions as permitted contextual modifiers', methodRefs: ['positional_context'] },
  { feature: 'Month Command facts within current scope', methodRefs: ['month_command'] },
  { feature: 'Yin/Yang composition', methodRefs: ['yin_yang_polarity'] },
  { feature: 'accepted Wu-Xing tally as structure, never as a personality score', methodRefs: ['wu_xing_distribution'] },
  { feature: 'identity/recurrence facts authorised by fact_relations', methodRefs: ['fact_relations'] },
];
export const NEAR_NEIGHBOUR_SOURCE = lens('14');

/** Section 16: an LLM judge may assist; it is never the sole oracle for these. */
export const LLM_JUDGE_NEVER_SOLE_ORACLE_FOR = [
  'claim support', 'sellability', 'specificity', 'customer truth', 'Golden-Reading acceptance',
] as const;
export const LLM_JUDGE_SOURCE = lens('16');

/** Everything the envelope assembles into the bundle. */
export const SEMANTIC_ENVELOPE = {
  epistemicLevels: EPISTEMIC_LEVELS,
  epistemicLevelsSource: EPISTEMIC_LEVELS_SOURCE,
  epistemicHardLaw: EPISTEMIC_HARD_LAW,
  tenGodFamilies: TEN_GOD_FAMILIES,
  tenGodVariants: TEN_GOD_VARIANTS,
  variantHardRule: VARIANT_HARD_RULE,
  depthOperators: DEPTH_OPERATORS,
  surfaceInteriorNeverInfer: SURFACE_INTERIOR_NEVER_INFER,
  surfaceInteriorSource: SURFACE_INTERIOR_SOURCE,
  claimTypes: CLAIM_TYPES,
  claimTypesSource: CLAIM_TYPES_SOURCE,
  languagePosture: LANGUAGE_POSTURE,
  metaphorRule: METAPHOR_RULE,
  reflectionJobs: REFLECTION_JOBS,
  antiMystificationForbidden: ANTI_MYSTIFICATION_FORBIDDEN,
  antiMystificationSource: ANTI_MYSTIFICATION_SOURCE,
  evaluationDimensions: EVALUATION_DIMENSIONS,
  evaluationDimensionsSource: EVALUATION_DIMENSIONS_SOURCE,
  barnumRiskPatterns: BARNUM_RISK_PATTERNS,
  barnumRiskSource: BARNUM_RISK_SOURCE,
  nearNeighbourFeatures: NEAR_NEIGHBOUR_FEATURES,
  nearNeighbourSource: NEAR_NEIGHBOUR_SOURCE,
  llmJudgeNeverSoleOracleFor: LLM_JUDGE_NEVER_SOLE_ORACLE_FOR,
  llmJudgeSource: LLM_JUDGE_SOURCE,
} as const;
export type SemanticEnvelope = typeof SEMANTIC_ENVELOPE;
